blog_v2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogapp/', include('blogapp.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

blogapp/urls.py
from django.urls import path
from blogapp import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

urlpatterns = [
    path('change-password/', auth_views.PasswordChangeView.as_view(success_url = reverse_lazy('password_changed')), name='change-password'),
    path('', views.index, name='index'),
    path('signin', views.user_signin, name='signin'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('password_changed/', views.password_changed, name='password_changed'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('post/<int:id>/', views.view_post, name='post'),
    path('delete_com/<int:id>/', views.delete_com, name='delete'),
    path('edit_comment/<int:id>/', views.edit_comment, name='edit'),
    path('create_post', views.create_post, name='create_post'),
    path('message/<int:id>/', views.message, name='message')

]

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    date_time = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)
    b_day = models.DateField(verbose_name='Дата рождения', blank=True)
    skype = models.CharField('Skype', max_length=250, blank=True)
    facebook = models.URLField('Facebook', blank=True)
    about = models.TextField('About', blank=True)

    def __str__(self):
        return '{0} - {1}'.format(self.user.username, self.about)

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=250)
    text = models.TextField('Пост')
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    date_time = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.title, self.text[:150] ,self.date_time)

class Comment(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, verbose_name='Пост', on_delete=models.CASCADE)
    text = models.TextField('Коментарий', blank=True)
    date_time = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)

    def __str__(self):
        return self.text


class Message(models.Model):
    _meg_list = []
    text = models.TextField('message')
    date_time = models.DateTimeField(verbose_name='Дата', auto_now_add=True, null=True)
    read = models.BooleanField(verbose_name='Прочитано')
    sender = models.ForeignKey(User, verbose_name='Отправыитель', on_delete=models.CASCADE, related_name="user_s")
    receiver = models.ForeignKey(User, verbose_name='Получатель', on_delete=models.CASCADE, related_name="user_r")

    def __str__(self):
        return '{0} - {1} ({2})'.format(self.text[:150], self.sender.username, self.read)

    def __init__(self, *args, **kwargs):
        self.__class__._meg_list.append(self)
        super(Message, self).__init__(*args, **kwargs)

    # def __new__(self, *args, **kwargs):
    #     self.__class__._meg_list.append(self)
    #     super(Message, self).__new__(*args, **kwargs)



    def unread(self):
        # return len(self.__class__._meg_list)
        return self.sender.user_r.filter(read=False).count()
        # return Message.objects.filter(read=False).count()

blogapp/forms.py
from django.forms import ModelForm, Form
from django import forms
from .models import *

# class ProfileForm(Form):
#     name = forms.CharField(widget=forms.TextInput(), label='Имя')
#     email = forms.EmailField (widget=forms.EmailInput())
#     password = forms.CharField(widget=forms.PasswordInput())
#
#     b_day = forms.DateField(widget=forms.DateInput(format='%m/%d/%Y'), label='День рождения')
#     skype = forms.CharField(widget=forms.TextInput())
#     facebook = forms.URLField(widget=forms.URLInput())
#     about = forms.CharField(widget=forms.Textarea(), label='Пару слов о себе')




class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        # widgets = {'password': forms.PasswordInput}


# class LoginForm(ModelForm):
#     class Meta:
#         model = User
#         fields = ['username', 'password']
#         widgets = {'password': forms.PasswordInput}

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [ 'b_day', 'skype', 'facebook', 'about']
        widgets = {'b_day': forms.SelectDateWidget(years=range(1930,2010))}


# class PostForm(ModelForm):
#     class Meta:
#         model = Post
#         fields = [ 'title', 'post']

blogapp/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, logout, login
from django.urls import reverse
from .forms import *
from .models import *
from django.db.models import Q


# Create your views here.

def index(request):
    user_list = User.objects.all()
    return render(request, 'blogapp/index.html', {'user_list': user_list})


def not_ready(request):
    return HttpResponse("Стрвница не готова")


def user_signin(request):
    if request.method == 'POST':
        userform = UserForm(request.POST)
        profileform = ProfileForm(request.POST)
        # print(request.POST["username"])
        # print(request.POST["password"])
        if userform.is_valid() and profileform.is_valid():
            user = userform.save()
            user.set_password(request.POST["password"])
            user.save()
            profileform.instance.user = user
            profileform.save()
            return redirect(reverse('index'))
    else:
        userform = UserForm()
        profileform = ProfileForm()
    return render(request, 'blogapp/signin.html', {'userform': userform, 'profileform': profileform})


def user_logout(request):
    logout(request)
    return redirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        data = request.POST
        # print(data['username'])
        # print(data['password'])

        user = authenticate(username=data['username'], password=data['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('index'))
            else:
                return render(request, 'blogapp/ERROR.html',
                              {'msg': 'The password is valid, but the account has been disabled!'})
        else:
            return render(request, 'blogapp/ERROR.html', {'msg': 'The username and password were incorrect.'})
    else:
        return render(request, 'blogapp/login.html')


def view_post(request, id):
    if request.method == 'POST':
        data = request.POST
        new_comment = Comment()
        new_comment.text = data['text']
        new_comment.user = request.user
        new_comment.post = Post.objects.get(id=id)
        new_comment.save()

    post = Post.objects.get(id=id)
    return render(request, 'blogapp/post.html', {'post': post})


def delete_com(request, id):
    comment = Comment.objects.get(id=id)
    post = comment.post
    comment.delete()
    return redirect(reverse('post', args=[post.id]))
        # render(request, 'blogapp/post.html', {'post': post})


# def create_post(request):
#     if request.method == 'POST':
#         postform = PostForm(request.POST)
#         if postform.is_valid():
#             postform.instance.user = request.user
#             postform.save()
#             my_id = postform.id
#             return redirect(reverse('post'+ my_id +'/'))
#     else:
#         postform = PostForm()
#     return render(request, 'blogapp/create_post.html', {'postform': postform})

def create_post(request):
    if request.method == 'POST':
        data = request.POST
        new_post = Post()
        new_post.title = data['title']
        new_post.text = data['text']
        new_post.user = request.user
        new_post.save()
        post_id = new_post.pk
        return redirect(reverse('post', args=[post_id]))

    else:
        return render(request, 'blogapp/create_post.html')


def edit_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.method == 'POST':
        data = request.POST
        comment.text = data['text']
        comment.save()
        comment_id = comment.post.id
        return redirect(reverse('post', args=[comment_id]))
    else:
        return render(request, 'blogapp/edit_comment.html', {'comment': comment})


def password_changed(request):
    id = request.user.id
    # return HttpResponseRedirect(str(id)+ '/' )
    return render(request, 'blogapp/password_changed.html', {'id': id})


def profile(request, id):
    cur_user = User.objects.get(id=id)
    # cur_profile = cur_user.profile
    dic = {'cur_user': cur_user}
    return render(request, 'blogapp/profile.html', dic)


def edit_profile(request):
    if request.method == 'POST':
        profileform = ProfileForm(request.POST)
        if profileform.is_valid():
            cur_user = request.user
            cur_profile = cur_user.profile
            cur_user.email = request.POST['email']
            cur_profile.b_day = request.POST['b_day_year'] + '-' + request.POST['b_day_month'] + '-' + request.POST[
                'b_day_day']
            cur_profile.skype = request.POST['skype']
            cur_profile.facebook = request.POST['facebook']
            cur_profile.about = request.POST['about']



            cur_user.save()
            cur_profile.save()
            return redirect(reverse('profile', args=str(cur_user.id)))
    else:

        # profile = Profile.objects.get(user=request.user)
        profile = request.user.profile
        init = {
            'b_day': profile.b_day,
            'skype': profile.skype,
            'facebook': profile.facebook,
            'about': profile.about,
        }

        # user = UserForm(initial = {'email' : request.user.email})
        profileform = ProfileForm(initial=init)

    return render(request, 'blogapp/edit_profile.html', {'profileform': profileform})


def message(request,id):
    if request.method == 'POST':
        data = request.POST
        new_message = Message()
        new_message.text = data['text']
        new_message.sender = request.user
        new_message.receiver = User.objects.get(id=id)
        new_message.read = False
        new_message.save()
        return redirect(reverse('message', args=[id]))
    else:
        msg_snd = Message.objects.filter(sender__id=request.user.id).filter(receiver__id=id)
        msg_rcv = Message.objects.filter(receiver__id=request.user.id).filter(sender__id=id)
        msg = msg_rcv.union(msg_snd).order_by('date_time')
        for m in msg_rcv:
            if not(m.read):
                m.read = True
                m.save()

        usr = User.objects.all()


        # count = request.user.user_r.filter(read=False).count()

        u_list = []

        for u in usr:
            # condition = (Q(sender=request.user, receiver=u) | Q(sender=u, receiver=request.user))
            condition = Q(sender=u, receiver=request.user)

            count = Message.objects.filter(condition).filter(read=False).count()
            if count > 0:
                count = '({0})'.format(count)
            else:
                count = ''
            u_list.append( {'user':u ,'count': count})
        # s_msg = request.user.user_s.all()




        # s_list = set()
        # for u in r_usr:
        #     r_list.append(u.filter(read=False).count())
        #     s_list.add(m.sender)
        # sr_list = r_list.union(s_list)




        # for u in usr:
        #     u_list.append(u.user_r.filter(sender__id=request.user.id).filter(receiver__id=id).count())

        dic = {'msg': msg, 'usr': usr, 'id':id, 'u_list':u_list}
        return render(request, 'blogapp/message.html', dic)

blogapp/templates/blogapp/ERROR.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ERROR</title>
</head>
<body>
{{msg}}
<br>
<a href="{% url 'index' %}">На главную</a>
</body>
</html>

blogapp/templates/blogapp/base_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<link rel="stylesheet" type="text/css" href="/static/blogapp/css/style.css">-->
<a href = "{% url 'index' %}">BLOG</a> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp


{% if user.is_authenticated %}
    Добро пожаловать, <a href="{% url 'profile' user.pk %}">{{ user.username }}</a>  <a href="{% url 'message' user.pk %}">лс({{count}}) ({{user.user_s.all.1.unread }})</a> | <a href="{% url 'logout' %}">logout</a>
{% else %}
   <a href="{% url 'login' %}">login</a> | <a href="{% url 'signin' %}">signin</a>
{% endif %}

<hr align="left" width="500" size="2" color="#000000" />


{% block content %}
{% endblock %}

</body>
</html>

blogapp/templates/blogapp/create_post.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<form  action="{% url 'create_post' %}" method="post">
    {% csrf_token %}
    <ul>
        <li>
            <label>Заголовок:</label>
            <input type="text" name="title">
        </li>
        <li>
            <label>Сообщение:</label>
            <textarea name="text" cols="40" rows="5"></textarea>
        </li>
        <li>
            <button type="submit">Отправить</button>
        </li>
    </ul>
</form>

{% endblock %}

blogapp/templates/blogapp/edit_comment.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<form  action="{% url 'edit' comment.id %}" method="post">
    {% csrf_token %}
    <ul>
        <li>
            <h2>Редоктирование коментария</h2>
        </li>
        <li>
            <label>Текст коментария:</label>
            <textarea name="text" cols="40" rows="5">{{comment.text}}</textarea>
        </li>
        <li>
            <button type="submit">Сохранить</button>
        </li>
    </ul>
</form>

{% endblock %}

blogapp/templates/blogapp/edit_profile.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<form  action="{% url 'edit_profile' %}" method="post">
    {% csrf_token %}
    <ul>
        <li>
            <h2>{{user}}</h2>
        </li>
        <li>
            <a href="{% url 'change-password' %}">change-password</a><br><br>
        </li>
        <li>
            <label for="id_email">Email address:</label>
            <input type="email" name="email" value={{ user.email}} maxlength="254" id="id_email">
        </li>
        <li>
            {{ profileform.as_p }}
        </li>
        <li>
            <button type="submit">Сохранить</button>
        </li>
    </ul>
</form>

{% endblock %}

blogapp/templates/blogapp/index.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

{% for u in user_list %}
<ul>
    <li>
        <b>Пользователь:</b>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' u.id %} "> {{u.username}} </a></b><br>
        {% else %}
            {{u.username}}
        {% endif %}
    </li>
    <ul>
        {% for post in u.post_set.all %}
            <li>
                <a href="{% url 'post' post.id%}">{{ post.title }}</a>
            </li>
        {% endfor %}

    </ul>
</ul>
    {% endfor%}
<br>
{% if user.is_authenticated %}
    <button onclick="window.location.href = '{% url 'create_post' %}';">Создать пост</button>
{% endif %}




{% endblock %}

blogapp/templates/blogapp/login.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<form  action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <ul>
        <li>
            <label>Имя пользователя:</label>
            <input type="text" name="username">
        </li>
        <li>
            <label>Пароль:</label>
            <input type="password" name="password">
        </li>
        <li>
            <button type="submit">Log in</button>
        </li>
    </ul>
</form>
{% endblock %}

blogapp/templates/blogapp/message.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<table border="1">
    <tr >
        <td width="100">
            <!--{% for u in usr %}-->
                <!--{% if u.id != user.id%}-->
                    <!--{% if u.id == id %}-->
                        <!--<p><b>{{u}}</b></p>-->
                    <!--{% else %}-->
                       <!--<p><a href="{% url 'message' u.id %}">{{u}}</a></p>-->
                        <!--&lt;!&ndash;{{ u.user_r.filter.count}}&ndash;&gt;-->
                        <!--&lt;!&ndash;{{u_list.}}&ndash;&gt;-->
                        <!--&lt;!&ndash;{{u_list.user}} &ndash;&gt;-->
                    <!--{% endif %}-->
                <!--{% endif %}-->
            <!--{% endfor %}-->



            {% for u in u_list %}
                {% if u.user.id != user.id %}
                    {% if u.user.id == id %}
                        <p><b>{{u.user}} {{u.count}}</b></p>
                    {% else %}
                       <p><a href="{% url 'message' u.user.id %}">{{u.user}} {{u.count}}</a></p>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </td>
        <td>
            {% for m in msg %}
                <p><b>{{m.sender.username}}</b>      <i>{{m.date_time}}</i></p>
                <p>{{m.text}}</p>
                <hr align="left" width="400" size="2" color="#555555" />
            {% endfor %}
            <form  action="{% url 'message' id %}" method="post">
                {% csrf_token %}
                <textarea name="text" cols="60" rows="5"></textarea><br>
                <button type="submit">Отправить</button>
            </form>
        </td>


    </tr>
</table>



{% endblock %}

blogapp/templates/blogapp/password_changed.html
<h2>Password changed</h2>

<head>
  <meta http-equiv='refresh' content='1; URL= {% url 'edit_profile' %}'>
</head>

blogapp/templates/blogapp/post.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<ul>
    <li>
        <b>Звголовок:</b>
        {{post.title}}
    </li>
    <li>
        <b>Дата создания:</b>
        {{post.date_time}}
    </li>
    <li>
        <b>Пост:</b>
        {{post.text}}
    </li>
</ul>

{% if user.is_authenticated %}
    <ul>
        {% for com in post.comment_set.all %}
            <li>
                <b>{{com.user}}</b> - {{ com.date_time}}<br>
                {{ com.text}}<br>
                {% if post.user == user %}
                    <a href="{% url 'delete' com.id %}">delete</a>
                {% endif %}

                {% if com.user == user %}
                    <a href="{% url 'edit' com.id %}">edit</a>
                {% endif %}
            </li>
        {% endfor%}
    </ul>

    <form  action="{% url 'post' post.id %}" method="post">
        {% csrf_token %}
        <label>Оставить коментарий:</label>
        <textarea name="text" cols="40" rows="5"></textarea>
        <button type="submit">Отправить</button>
    </form>
{% else %}
    <a href="{% url 'login' %}">чтобы прочесть комментарии авторизуйся</a>
{% endif %}


</ul>
{% endblock %}

blogapp/templates/blogapp/profile.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<ul>
    <li>
        <b>{{cur_user.username}}</b> &nbsp&nbsp&nbsp&nbsp <i>Зарегистрирован {{cur_user.profile.date_time }}</i>
    </li>
    <li>
        <b>Имя:</b>
        {{ cur_user.get_full_name }}
    </li>
    <li>
        <b>Email:</b>
        {{cur_user.email}}
    </li>
    <li>
        <b>Дата рождения:</b>
        {{cur_user.profile.b_day }}
    </li>
    <li>
        <b>Skype:</b>
        {{cur_user.profile.skype }}<br>
    </li>
    <li>
        <b>Facebook:</b>
        {{cur_user.profile.facebook}}<br>
    </li>
    <li>
        <b>About:</b>
        {{cur_user.profile.about}}<br>
    </li>
    <li>

    </li>
</ul>

{% if user.is_authenticated %}
    {% if cur_user == user %}
        <a href="{% url 'edit_profile' %}">Редактировать профиль</a>
    {% else %}
        <a href="{% url 'message' cur_user.id %}">Отправить личное сообщение</a>
    {% endif %}
{% endif %}

{% endblock %}

blogapp/templates/blogapp/signin.html
{% extends 'blogapp/base_index.html' %}
{% block content %}

<form  action="{% url 'signin' %}" method="post">
    {% csrf_token %}
    <ul>
        <li>
            {{ userform.as_p }}
        </li>
        <li>
            {{ profileform.as_p }}
        </li>
        <li>
            <input type="submit">
            <!--<button type="submit">Sigh in</button>-->
        </li>
    </ul>
</form>

{% endblock %}